name: Docker Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'
  push:
    branches:
      - main
      - develop
      - docker/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  docker-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - alpine
          - archlinux
          - centos
          - clearlinux
          - debian
          - fedora
          - mingw
          - ubuntu
          - quickstart
    name: Docker ${{ matrix.runtime }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: ${{ matrix.runtime }}
        shell: 'script -q -e -c "bash {0}"'
        run: bash ./test/runtime --driver docker --build --run ${{ matrix.runtime }}
  example-docker:
    runs-on: ubuntu-latest
    name: Test Dockerfile on the repo root
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build . -t otiai10/gosseract
      - name: Test Run
        run: docker run -i --rm otiai10/gosseract
